# Generated by Django 3.2.9 on 2023-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=255, unique=True)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
