# Generated by Django 3.2.9 on 2023-08-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0002_auto_20230824_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitcount',
            old_name='url_path',
            new_name='endpoint',
        ),
    ]
