# Generated by Django 3.2.9 on 2023-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0003_rename_url_path_hitcount_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='endpoint',
            field=models.CharField(max_length=255000000000000000, unique=True),
        ),
    ]
