# Generated by Django 3.2.9 on 2023-08-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0004_alter_hitcount_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='endpoint',
            field=models.CharField(max_length=255000000000000000),
        ),
    ]
